# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('path_to_bin', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='classifier',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='classifier',
            name='path_to_bin',
        ),
        migrations.RemoveField(
            model_name='classifier',
            name='price',
        ),
        migrations.RemoveField(
            model_name='classifier',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='classifier',
            name='discription',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Topic'),
        ),
        migrations.AddField(
            model_name='classifierversion',
            name='topics',
            field=models.ManyToManyField(to='app.Topic'),
        ),
        migrations.AddField(
            model_name='classifier',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ClassifierVersion'),
        ),
    ]
