# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_classifier_path_to_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='status',
            field=models.CharField(default='Не обучен', max_length=8),
        ),
    ]
