# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171208_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='parent',
            new_name='classifier',
        ),
    ]
