# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171208_1049'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('name', 'classifier')]),
        ),
    ]
